export enum ResponseCodes{
    SUCCESS = 'SUCCESS',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    UNALLOWED_METHOD = 'UNALLOWED_METHOD',
    ALL_FIELDS_REQUIRED = 'ALL_FIELDS_REQUIRED',
    PASSWORDS_NOT_MATHES = 'PASSWORDS_NOT_MATHES'
}